services:
  client:
    build: 
      context: ./client
      dockerfile: dockerfile.client
      target: production
    ports:
      - "${PORT:-80}:80"
    depends_on:
      - server
    environment:
      - PORT=${PORT}
  server:
    build: 
      context: ./server
      dockerfile: dockerfile.server
      target: production
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
